#pagebreak()
= Conclusiones

Con el desarrollo del "Sistema de Gestión de Vacantes de Empleo" (SGVac), logramos alcanzar los objetivos que nos planteamos al inicio del proyecto, adaptándonos a las necesidades reales de la gestión de recursos humanos. A lo largo de este trabajo, no solo aplicamos los conocimientos que adquirimos durante la carrera de Ingeniería en Computación, sino que también nos desafiamos a profundizar en tecnologías modernas como los _containers_, lo que ha sido fundamental para nuestra formación profesional.

Conseguimos centralizar un proceso que, habitualmente, se encontraba disperso. Notamos que la gestión de vacantes solía depender de cadenas de correos o planillas difíciles de seguir; con nuestro sistema, optimizamos el tiempo necesario. Además, consideramos que la funcionalidad de personalización visual para cada empresa agrega un valor distintivo, ya que logramos que cada organización mantenga su propia identidad frente a los candidatos.

Gracias a la arquitectura web que elegimos, basada en React y Node.js, aseguramos que el sistema sea accesible desde cualquier dispositivo. Pusimos especial énfasis en el diseño _responsive_ del portal público, considerando que en la actualidad la mayoría de los postulantes buscan empleo desde su celular. En cuanto a la seguridad, al integrar Firebase para los postulantes, garantizamos un manejo sólido de las identidades, protegiendo tanto los currículums como los datos corporativos.

Durante el desarrollo, nos enfrentamos a varios desafíos técnicos interesantes. Uno de los más complejos fue diseñar la base de datos en MariaDB para que soportara una arquitectura multiempresa, asegurándonos de que los datos de un cliente fueran invisibles para los otros. Por otro lado, la decisión de unificar todo el desarrollo bajo TypeScript fue un reto inicial, pero nos dimos cuenta de que, a la larga, iba a reducir drásticamente los errores de código.

Diseñamos interfaces diferenciadas porque entendimos que nuestros usuarios tienen necesidades distintas: buscamos eficiencia para los administradores usando Material UI, y una experiencia ágil y moderna para los postulantes. Mediante las pruebas de estrés y usabilidad que realizamos, pudimos verificar que el sistema es robusto y capaz de soportar la concurrencia propia de un entorno laboral activo.

Para concluir, consideramos que el SGVac no solo resuelve la problemática operativa de publicar vacantes de trabajo, sino, que también establece una infraestructura sólida y escalable. Estamos convencidos de que, con esta base tecnológica, el sistema está listo para evolucionar, y dejamos el camino preparado para futuras mejoras, como la incorporación de inteligencia artificial para la clasificación de candidatos.