#pagebreak()
= Introducción

Este documento corresponde al trabajo de graduación de la carrera de Ingeniería en Computación de la Facultad de Ciencias Exactas y Tecnología de la Universidad Nacional de Tucumán. El proyecto consiste en el desarrollo de un sistema integral denominado SGVac (Sistema de Gestión de Vacantes), el cual surge como respuesta a la necesidad de contar con una plataforma centralizada y multiempresa para la administración de ofertas laborales y procesos de selección.

El sistema permite la gestión simultánea de múltiples empresas, donde cada una opera de manera independiente dentro de la misma plataforma. Los administradores de cada empresa pueden crear, modificar y publicar vacantes de empleo, organizándolas mediante categorías personalizadas que se ajustan a su rubro específico. Además, el sistema facilita la interacción con los candidatos, permitiendo a los postulantes registrarse, cargar su currículum vitae y aplicar a las ofertas disponibles, manteniendo un historial detallado de sus postulaciones.

Asimismo, se implementó un sistema robusto de asignación de roles que establece distintos niveles de responsabilidad y acceso. El rol de Superadministrador posee una visión global del sistema y es responsable de gestionar el alta y baja de las empresas clientes y sus recursos. En contraste, el rol de Administrador opera exclusivamente dentro del ámbito de su empresa, administrando vacantes y evaluando postulantes, mientras que el rol de Postulante accede a las funcionalidades públicas de búsqueda y postulación.

A partir de todas las funcionalidades mencionadas, el sistema cuenta con características avanzadas de personalización, permitiendo a cada empresa configurar estilos visuales propios para brindar una experiencia de marca única a sus candidatos. La plataforma fue diseñada con un enfoque _responsive_, garantizando que tanto la gestión administrativa como la búsqueda de empleo sean accesibles y funcionales desde cualquier dispositivo, ya sea móvil o de escritorio.

Este sistema tiene como objetivo optimizar el flujo de reclutamiento, centralizando la información de vacantes y postulantes de manera segura y eficiente, y ofreciendo una herramienta flexible que se adapta tanto a las necesidades de gestión de las empresas como a la experiencia de usuario de los candidatos.